import os
from dotenv import load_dotenv

load_dotenv()

RABBIT_HOST = os.getenv('RABBIT_HOST')
RABBIT_PORT = os.getenv('RABBIT_PORT')
FIRST_TRAFFIC_LIGHT = os.getenv('FIRST_TRAFFIC_LIGHT')
SECOND_TRAFFIC_LIGHT = os.getenv('SECOND_TRAFFIC_LIGHT')
THIRD_TRAFFIC_LIGHT = os.getenv('THIRD_TRAFFIC_LIGHT')
FOURTH_TRAFFIC_LIGHT = os.getenv('FOURTH_TRAFFIC_LIGHT')

FIRST_CONNER_TRAFFIC_LIGHT = os.getenv('FIRST_CONNER_TRAFFIC_LIGHT')
SECOND_CONNER_TRAFFIC_LIGHT = os.getenv('SECOND_CONNER_TRAFFIC_LIGHT')
THIRD_CONNER_TRAFFIC_LIGHT = os.getenv('THIRD_CONNER_TRAFFIC_LIGHT')
FOURTH_CONNER_TRAFFIC_LIGHT = os.getenv('FOURTH_CONNER_TRAFFIC_LIGHT')